finished 4.1 Mike Fight Scribble cutscence
jalenng/Draw pull request #14
Opened 2022-11-16 05:47 UTC by natashalukmanto

2023-08-18 06:41 UTC, rykwong approved these changes

2023-08-19 07:37 UTC, jalenng requested changes

2023-08-19 07:37 UTC, jalenng commented on Assets/Scripts/Dialogue/DialogueEntry.cs.meta
> +>>>>>>> finished 4.1 Mike Fight Scribble Cutscence:Assets/Scripts/OrangeObjectTrigger.cs.meta
@rykwong unresolved merge conflicts here, let's remove this change

2023-08-19 07:37 UTC, jalenng commented on Assets/Scripts/UI/LevelSelector.cs.meta
> +>>>>>>> main:Assets/Scripts/UI/LevelSelector.cs.meta
unresolved merge conflicts

2023-08-19 07:37 UTC, jalenng commented on Assets/Sprites/Ground Pieces/Nathan Part 2.meta
> +>>>>>>> 3e744df919b7a46f414d61a679286508bd3c0567:Assets/Scenes/Levels/Mike Part 1 - Copy Natasha.unity.meta
unresolved merge conflicts

2023-08-19 07:46 UTC, jalenng approved these changes

2023-08-19 07:47 UTC, merged